upstream backend_server {
    server backend:8000;
}
upstream frontend_server {
    server frontend:8000;
}

server {
    listen 80;
    server_name localhost _;
    client_max_body_size 25M; #Safe for Cloudflare tunnel

    location = /favicon.ico {
        alias /app/favicon.ico;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://frontend_server/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass_header  Cache-Control;
        gzip on;
        #gzip_types application/json text/plain;
        access_log off;
        add_header Cache-Control $cache_control_fallback;
    }
    location /api {
        proxy_pass http://backend_server/api;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto 'https';
        access_log on;
        gzip_types application/json text/plain;
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }
    location /admin {
        proxy_pass http://backend_server/admin;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto 'https';
        access_log on;
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }
    location /static {
        alias /app/django/static;
        expires 7d;
        try_files $uri =404;
        gzip on;
        gzip_types application/json text/plain application/javascript text/javascript;
        access_log off;
    }
    location / {
        return 301 https://admin.zenvms.app/site-admin;
    }
}
